spring:
  application:
    name: gateway

  cloud:
    config:
      uri: http://localhost:8888
      label: main

  config:
    import: optional:configserver:http://localhost:8888

  main:
    web-application-type: reactive
